name: "Build SQL Server Project"
description: "Builds a SQL Server Project with MSSBuild"
inputs:
  project-path:
    description: "Path of the SQL project"
    required: true
    default: "."
runs:
  using: "composite"
  steps:
    - run: echo ${{ inputs.project-path }}
