name: "Build SQL Server Project"
description: "Builds a SQL Server Project with MSSBuild"
inputs:
  project-path:
    description: "Path of the SQL project"
    required: true
  msbuild-configuration:
    description: "MSSBuild configuration"
    required: false
    default: "Release"
  archive-file-path:
    description: "File path SQL project artifacts should be archived to"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - uses: microsoft/setup-msbuild@v1
    - name: Build SQL project
      shell: pwsh
      run: |
        msbuild ${{ inputs.project-path }} /nologo /nr:false `
          /p:configuration="${{ inputs.msbuild-configuration }}" `
          /p:DSP="Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider"

    - name: "Push artifacts"
      if: ${{ inputs.archive-file-path != '' }}
      shell: pwsh
      run: |
        Compress-Archive -Path ${{ inputs.project-path }}\bin\${{ inputs.msbuild-configuration }}\* -DestinationPath ${{ inputs.archive-file-path }} -Force
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add ${{ inputs.archive-file-path }}
        git commit -m "Build output"
        git push
