name: "Build SQL Server Project"
description: "Builds a SQL Server Project with MSSBuild"
inputs:
  project-path:
    description: "Path of the SQL project"
    required: true
  msbuild-configuration:
    description: "MSSBuild configuration"
    required: false
    default: "Release"
runs:
  using: "composite"
  steps:
    - uses: microsoft/setup-msbuild@v1
    - name: Build SQL project
      shell: pwsh
      run: |
        msbuild ${{ inputs.project-path }} /nologo /nr:false `
          /p:configuration="${{ inputs.project-path }}" `
          /p:DSP="Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider"
